version: '3.8'

services:
  app:
    image: ruby-3.3.8v1
    container_name: Buggy_rails_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "
        bundle install &&
        bundle exec rake db:create db:migrate &&
        bundle exec rails assets:precompile &&
        bundle exec puma -C config/puma.rb
      "

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

volumes:
  mysql_data:
