default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER']|| "root" %>
  password: <%= ENV['MYSQL_PASSWORD']  || "password" %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PROD'] || "myapp_production" %>

